<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [6]:
x = 10
assert x >= 0, "x is becoming negative!"

#assert is to assert the message and stop executing the moment the condition becomes false. 

In [8]:
x = -10
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [ ]:
number = input("Give me a number and I will calculate its square.")
square = int(number) ** 2
print(f"The square of {number} is {square}!")

#Will give a value error as I have input an invalid answer if I put string. 

In [15]:
try:
    number = input("Give me a number and I will calculate its square.")
    square = int(number) ** 2
    print(f"The square of {number} is {square}!")
          
except:
    print(f"Oh oh! I cannot square {number}!")
    
#Except will remove every possible error that appears. 
#But might not be good also if there're some underlying issues in my code??

Give me a number and I will calculate its square.ha
Oh oh! I cannot square ha!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [20]:
def funny_add(a, b, c = 1):
    return a + 10*b + 100*c
funny_add(1, 2, 3)

321

In [21]:
funny_add(c = 3, a = 2, b = 1)

312

In [ ]:
#I didn't think funny_add(a = 2, 1) will not work as I thought it will assign b as 1, c as 1. 
#OK keyword cannot be after positional. 

### 2.2 Docstrings

In [23]:
def funny_add(a, b, c=1):
    """
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work
    """
    return a + 10*b + 100*c

help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work



### 2.3 Function are first class citizens

In [5]:
def my_function(angle, trig_function):
    return trig_function(angle)

my_function(np.pi/2, np.sin)

#Can use round function to show the exact decimals. 

1.0

In [6]:
my_function(np.pi/2, np.cos)

#Am I tripping but why is it not 0???? Why is it not exact?

6.123233995736766e-17

In [26]:
my_function(np.pi/2, lambda x: np.cos(2*x))

#I think I can see how x is pi/2, but it seems so unintuitive. 

-1.0

### 2.4 More unpacking

In [27]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [33]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [34]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

#What's the logic as to how the python interpreter interprets the * operator???
#* means keep the number of values flexible. 

1 [2, 3, 4] 5


In [35]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


In [8]:
x, y, *z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 2 [3, 4, 5]


## Exercise 1 :  A better calculator I

In [2]:
def add(x, y):
    assert type(x) == int or np.array and type(y) == int or np.array, "Insert an integer!"
    return x + y
#Idk if this is a possible exception to take note of, I had to specifically include np.array if not x & y would
#Not work. 

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    assert all(y != 0), "y cannot be 0!"
    return x / y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

divide(x, y)

#ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
#This error pops up quite frequently and idk what's causing it.
#I'm not sure why the any() function solves this problem.
# Solved.

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [9]:
# Attempt 2
# Will not create assertions for the others except division
# As there are too many data types that can undergo arithmetic 
# And too many considerations will make code unreadable. 
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    assert 0 not in y, "y cannot be 0!"
    return x / y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

divide(x, y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 2 :  A better calculator II

In [5]:
def add(x, y):
    try:
        return x + y
    except:
        return "Insert an integer!"

def subtract(x, y):
    try:
        return x - y
    except:
        return "Insert an integer!"

def multiply(x, y):
    try:
        return x * y
    except:
        return "Insert an integer!"
    
def divide(x, y):
    try:
        return x / y
    except ZeroDivisionError:
        return "y cannot be 0!"
    except:
        return "Insert an integer"

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 34])

divide(x, y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.79411765])