<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np

# Python Lists

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

# Numpy Arrays

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

# Dictionary 
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                 }
                  

### 1.2 Accessing data from a list (or array)

In [2]:
hero_names = ["Black Widow", "Iron Man", "Doctor Strange"]
real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(hero_names[0])
print(real_names[0])
print(hero_names[2])
print(hero_names[-1])

#Calling the list will just output the data e.g. hero_names[0]

Black Widow
Natasha Romanoff
Doctor Strange
Doctor Strange


'Iron Man'

In [3]:
#Trying it as an array:
hero_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

(hero_names[0])

'Black Widow'

### 1.3 Accessing data from a dictionary

In [12]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Natasha Romanoff"])
superhero_info.keys()
superhero_info.values()

Black Widow


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [3]:
py_superhero_info = [["Natasha Romanoff", "Black Widow"],
                     ["Tony Stark", "Iron Man"],
                     ["Stephen Strange", "Doctor Strange"]]

print(py_superhero_info[0][0])

Natasha Romanoff


## 2 Lists vs. Arrays

### 2.1 Size

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"], [5, "E"],
              [6, "F"], [7, "G"], [8, "H"], [9, "I"], [10, "J"]]
              
np_array_2d = np.array(py_list_2d)

len(py_list_2d)
len(np_array_2d)
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [22]:
py_list = [1, 1.5,  'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [10]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

np_array + 10

#py_list + 10 will give error

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [3]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2 

np_array_1 + np_array_2

#Lists will combine the data values together, arrays will perform arthimetic ig

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [32]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

py_list * 2

#Data in lists are treated as str?

np_array * 2

#Math is actually performed in the array

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [4]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

#py_list ** 2 don't work as exponential is nonsupported operator in list!

np_array ** 2

#Works for this as can perform math

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [39]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

py_list == 3

#I think it's asking if the entire list is 3, which is false?
#No circumstances where a list can be equal to an integer.

np_array == 3

#Goes through the entire array from left to right and checks if the criteria is true/false. 

np_array > 3


array([False, False, False,  True,  True])

### 2.8 Mathematics

In [5]:
py_list = [1, 2, 3, 4, 5]
renamed_array = np.array(py_list)

sum(py_list)
max(py_list)
min(py_list)

#py_list.sum()

#Doesn't work cos it's a numpy sum function, will not work on py list.

renamed_array.sum()
renamed_array.mean()
renamed_array.max()
renamed_array.min()

1

## Exercise 1 :  Total recall?

**1. Two similarities between lists and arrays**

- Lists and arrays are able to store data by enclosing them in [ ] and separating the data with a ,
- _Both allow you to access data inside the list/array and output them._

**2. Two differences between list and arrays.**
- List is from python, an array requires an import from numpy first.
- List is more accomodating in taking in multiple data types, while an array can only take in a single data type.
- _Arithmetic will not work on a list (+10) but works on array. A list acts like a str in some sense where 2 lists can be concentenated together with + instead of adding the datas inside. (Correct me if wrong!)_


**3. What is a dictionary?**
- A dictionary works as a key and value system, enclosed with {} parantheses. It stores the keys on the left side, and returns the values stored on the right when called for. 
- _To output the return value, use ```print(dictionary_name["key"])```_

## Exercise 2 :  Index me

In [50]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    
print(py_list[::2])

['a1', 'c3', 'e5', 'g7', 'i9']


## Exercise 3 :  Capitalise Heros

In [6]:
superhero_info = {"Natasha Romanoff": "Black Widow".upper(),
                  "Tony Stark": "Iron Man".upper(),
                  "Stephen Strange": "Doctor Strange".upper()
                  } 

print(superhero_info["Stephen Strange"])

DOCTOR STRANGE


## Exercise 4 :  How many ones

In [6]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]  

np_numbers = np.array(numbers)

(np_numbers == 1).sum()


#As output is 9, means that there are nine 1 in this list. 
#Not sure if this is the ideal method as it doesnt work for counting other numbers outside 1. 
#Correction: It adds the frequncy of 1 (true), not the value of 1.

9

In [12]:
np_numbers == 1

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])